apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "64"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"haios-test-deployment","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"haios-test"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"haios-test"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"root"}],"image":"haios-mysql:8.0.36-debian-v1","imagePullPolicy":"IfNotPresent","name":"haios-mysql","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/log/mysql","name":"haios-mysql-log"},{"mountPath":"/var/lib/mysql","name":"haios-mysql-data"},{"mountPath":"/etc/mysql/my.cnf","name":"haios-mysql-config","readOnly":true}]},{"args":["test"],"command":["/app/D2VM/run.sh"],"envFrom":[{"configMapRef":{"name":"haios-config"}}],"image":"haios:v1.1.1","imagePullPolicy":"IfNotPresent","name":"haios","ports":[{"containerPort":32320,"name":"back-end-port","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/D2VM","name":"haios-app"},{"mountPath":"/app/D2VM/pod_config","name":"haios-app-pod-config"},{"mountPath":"/app/D2VM/logs","name":"haios-app-log"},{"mountPath":"/data/VM","name":"haios-share-volumes"},{"mountPath":"/root/.kube","name":"haios-kubelets-config","readOnly":true},{"mountPath":"/root/.ssh","name":"haios-ssh-config","readOnly":true}]}],"dnsPolicy":"Default","initContainers":[{"command":["sh","-c","chmod 1777 /tmp"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fix-tmp-permission","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/tmp","name":"tmp-volume"}]}],"nodeSelector":{"node-role.kubernetes.io/master":""},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/nfs-data/haios/mysql/data"},"name":"haios-mysql-data"},{"hostPath":{"path":"/nfs-data/haios/mysql/log","type":""},"name":"haios-mysql-log"},{"hostPath":{"path":"/nfs-data/haios/mysql/conf/my.cnf","type":""},"name":"haios-mysql-config"},{"hostPath":{"path":"/nfs-data/VM/","type":""},"name":"haios-share-volumes"},{"hostPath":{"path":"/nfs-data/haios/pod_config","type":""},"name":"haios-app-pod-config"},{"hostPath":{"path":"/nfs-data/haios/logs","type":""},"name":"haios-app-log"},{"hostPath":{"path":"/nfs-data/haios/D2VM","type":""},"name":"haios-app"},{"hostPath":{"path":"/home/user/.kube","type":""},"name":"haios-kubelets-config"},{"hostPath":{"path":"/home/user/.ssh","type":""},"name":"haios-ssh-config"},{"emptyDir":{},"name":"tmp-volume"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-05-08T09:27:07Z","lastUpdateTime":"2025-05-08T10:24:22Z","message":"ReplicaSet \"haios-test-deployment-5d854fdf8f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-05-13T03:46:12Z","lastUpdateTime":"2025-05-13T03:46:12Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":7,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-05-26T09:15:37Z"
  generation: 64
  name: haios-test-deployment
  namespace: default
  resourceVersion: "7557937"
  uid: 1254a9be-2962-49c9-9c89-23b9dd2e453d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: haios-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-07T05:39:59Z"
      creationTimestamp: null
      labels:
        app: haios-test
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: haios-mysql:8.0.36-debian-v1
          imagePullPolicy: IfNotPresent
          name: haios-mysql
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/mysql
              name: haios-mysql-log
            - mountPath: /var/lib/mysql
              name: haios-mysql-data
            - mountPath: /etc/mysql/my.cnf
              name: haios-mysql-config
              readOnly: true
        - args:
            - test
          command:
            - /app/D2VM/run.sh
          envFrom:
            - configMapRef:
                name: haios-config
          image: haios:v1.1.1
          imagePullPolicy: IfNotPresent
          name: haios
          ports:
            - containerPort: 32320
              name: back-end-port
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/D2VM
              name: haios-app
            - mountPath: /app/D2VM/pod_config
              name: haios-app-pod-config
            - mountPath: /app/D2VM/logs
              name: haios-app-log
            - mountPath: /data/VM
              name: haios-share-volumes
            - mountPath: /root/.kube
              name: haios-kubelets-config
              readOnly: true
            - mountPath: /root/.ssh
              name: haios-ssh-config
              readOnly: true
        - name: mysql-sync
          image: 43.138.201.159:6655/sync_prod/sync:v1.1.0-yuanwuzhi
          env:
            - name: SYNC_CONFIG_PATH
              value: "/app/configs/config.yml"
          ports:
            - containerPort: 28081
          command: ["sh", "-c", "sleep 30; exec ./sync-tool"]
      dnsPolicy: Default
      initContainers:
        - command:
            - sh
            - -c
            - chmod 1777 /tmp
          image: busybox
          imagePullPolicy: IfNotPresent
          name: fix-tmp-permission
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - hostPath:
            path: /nfs-data/haios/mysql/data
            type: ""
          name: haios-mysql-data
        - hostPath:
            path: /nfs-data/haios/mysql/log
            type: ""
          name: haios-mysql-log
        - hostPath:
            path: /nfs-data/haios/mysql/conf/my.cnf
            type: ""
          name: haios-mysql-config
        - hostPath:
            path: /nfs-data/VM/
            type: ""
          name: haios-share-volumes
        - hostPath:
            path: /nfs-data/haios/pod_config
            type: ""
          name: haios-app-pod-config
        - hostPath:
            path: /nfs-data/haios/logs
            type: ""
          name: haios-app-log
        - hostPath:
            path: /nfs-data/haios/D2VM
            type: ""
          name: haios-app
        - hostPath:
            path: /home/user/.kube
            type: ""
          name: haios-kubelets-config
        - hostPath:
            path: /home/user/.ssh
            type: ""
          name: haios-ssh-config
        - emptyDir: {}
          name: tmp-volume
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-06-23T01:38:56Z"
      lastUpdateTime: "2025-06-23T01:38:56Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-05-27T06:56:00Z"
      lastUpdateTime: "2025-07-07T05:40:02Z"
      message: ReplicaSet "haios-test-deployment-6d5b4dcb55" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 64
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
